### ISSUE TITLE
error: Exited sync due to fetch errors

### ISSUE THREAD

**Issue by nicolaevladescu** [sonyxperiadev/device-sony-sirius#33]
Hello, i'm back with a new battery :+1:  and a new error :-1:  when syncing

```
Fetching project platform/external/vboot_reference
Fetching projects:  39% (192/490)  Fetching project camera
error: Cannot fetch camera (GitError: --force-sync not enabled; cannot overwrite a local work tree. If you're comfortable with the possibility of losing the work tree's git metadata, use `repo sync --force-sync hardware/qcom/camera` to proceed.)
Fetching project mkqcdtbootimg
Exception in thread Thread-196:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/nicolae/android/.repo/repo/subcmds/sync.py", line 265, in _FetchProjectList
    success = self._FetchHelper(opt, project, *args, **kwargs)
  File "/home/nicolae/android/.repo/repo/subcmds/sync.py", line 308, in _FetchHelper
    optimized_fetch=opt.optimized_fetch)
  File "/home/nicolae/android/.repo/repo/project.py", line 1147, in Sync_NetworkHalf
    self._InitGitDir(force_sync=force_sync)
  File "/home/nicolae/android/.repo/repo/project.py", line 2171, in _InitGitDir
    raise e
GitError: --force-sync not enabled; cannot overwrite a local work tree. If you're comfortable with the possibility of losing the work tree's git metadata, use `repo sync --force-sync hardware/qcom/camera` to proceed.

Fetching projects:  40% (196/490)
error: Exited sync due to fetch errors
```

**Comment by jerpelea** [comment]
as the message says you need 
repo sync --force-sync

**Comment by nicolaevladescu** [comment]
Ok, i suspected that was the answer but i wanted to check if i should do what the message says. It's not specified in the documentation page that this would happen, so i did not want to cause unexpected behavior by follow the on screen instruction. Thanks!
